### ISSUE TITLE
Unable to open the notebooks

### ISSUE THREAD

**Issue by ghost** [bkamins/JuliaCon2020-DataFrames-Tutorial#1]
I get the below error:
Unreadable Notebook: /Julia/DataFrames_JuliaCon2020/advanced.ipynb NotJSONError('Notebook does not appear to be JSON: \'\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang="...')

**Comment by FranklinChen** [comment]
You probably want the actual `.ipynb` file, rather than the Web page: https://raw.githubusercontent.com/bkamins/JuliaCon2020-DataFrames-Tutorial/master/indexing_part2_advanced.ipynb

**Comment by ghost** [comment]
Dang! Thanks!
